import = [
    "~/.config/alacritty/themes/themes/papercolor_light.toml"
]

[shell]
program = "/opt/homebrew/bin/bash"

[font]
size = 14
normal.family = "Droid Sans Mono"

[cursor]
style.blinking = "Never"

[window]
option_as_alt = "Both"

[mouse]
hide_when_typing = true
